### ISSUE TITLE
Outdated repository

### ISSUE THREAD

**Issue by Kusekushi** [firmadyne/qemu-linaro#2]
This repository seems to be just completely left alone and be based off of qemu 2.3

I'd actually suggest to have some patchsets in here instead of the whole source tree, since it IMO at least makes it kinda easier to update this repo as an "outsider" if you will.

**Comment by dbrumley** [comment]
Hi!  We published firmadyne many years ago, and from what I can tell, some people have forked it and even made successful commercial companies with the tech.

Happy to figure out a way to keep the OSS version live. My constraint: I don't have any students working on this anymore, and don't have the capacity myself.

Thoughts?

**Comment by Kusekushi** [comment]
Do you by any chance still have a list of extra changes that were done to this repo? I'd be more than willing to work on converting those to patchsets and bump qemu here to something recent.

As for the general thing - I suppose it's a good idea to simplify everything as much as possible so that others aren't as discouraged to look at this if that makes sense.

I guess let's start off with this repo - bump stuff and have patchsets if needed.

**Comment by ddcc** [comment]
I don't think this repository is super important, it has just one commit on top of upstream that hardcodes some EEPROM data for one specific type of router, but feel free to work on it!

**Comment by dbrumley** [comment]
@ddorando happy to make you a contributor if you'd like to update this repo.  The general firmadyne framework seems pretty useful, and it would be great to have volunteers maintaining it a bit better.   Just to confirm: ok to add you as a contributor?

**Comment by Kusekushi** [comment]
Sure thing!

**Comment by dbrumley** [comment]
Done. Closing this ticket for now.
